services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: dashboard-allinone:latest
    container_name: dashboard
    restart: unless-stopped
    environment:
      WS_HOST: "0.0.0.0"
      WS_PORT: "8080"

      # Configs PÃšBLICAS atualizadas
      PUBLIC_HOST: "formigarei.com.br"
      PUBLIC_PORT: "443"
      ALLOWED_ORIGINS: "https://formigarei.com.br"
      USE_WSS: "true"
      UPDATE_INTERVAL: "2"
    volumes:
      - ./app/static:/app/static:ro
    networks:
      - vps_network

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - vps_network

volumes:
  caddy_data:

networks:
  vps_network:
    driver: bridge
